import { join, relative, basename, dirname } from 'path';
import { promises as fs } from 'fs';
import type { BrowserWindow } from 'electron';
import { IPC, replaceWikiLinkTarget, parseFrontmatter, serializeFrontmatter } from '@notes-app/common';
import type { Frontmatter } from '@notes-app/common';
import { buildVaultIndex, watchVault, atomicWrite, mergeForSave } from '@notes-app/vault';
import type { VaultIndex, VaultWatcher } from '@notes-app/vault';

let currentVaultRoot: string | null = null;
let vaultIndex: VaultIndex | null = null;
let watcher: VaultWatcher | null = null;

export function getVaultRoot() {
  return currentVaultRoot;
}

export function getIndex() {
  return vaultIndex;
}

export async function openVault(vaultPath: string, win: BrowserWindow) {
  // Close previous watcher
  await watcher?.close();

  currentVaultRoot = vaultPath;
  vaultIndex = await buildVaultIndex(vaultPath);

  watcher = watchVault(vaultPath, async (event, absolutePath) => {
    if (!vaultIndex) return;
    const relativePath = relative(vaultPath, absolutePath);

    if (event === 'unlink') {
      vaultIndex.removeByPath(relativePath);
      win.webContents.send(IPC.VAULT_FILE_CHANGED, {
        event: 'unlink',
        relativePath,
      });
      return;
    }

    try {
      const record = await vaultIndex.addOrRefresh(absolutePath);
      win.webContents.send(IPC.VAULT_FILE_CHANGED, {
        event,
        relativePath,
        record,
      });
    } catch {
      // File may have been deleted immediately after event
    }
  });

  return vaultIndex.getAllNotes();
}

export async function readFile(relativePath: string): Promise<string> {
  if (!currentVaultRoot) throw new Error('No vault open');
  return fs.readFile(join(currentVaultRoot, relativePath), 'utf-8');
}

export async function writeFile(relativePath: string, body: string): Promise<void> {
  if (!currentVaultRoot) throw new Error('No vault open');
  const absPath = join(currentVaultRoot, relativePath);

  // Read existing file so we can preserve/merge frontmatter (ADR-0006).
  let rawExisting: string | null = null;
  try {
    rawExisting = await fs.readFile(absPath, 'utf-8');
  } catch {
    // File does not exist yet — mergeForSave handles null gracefully.
  }

  // Use the in-memory id already held in the index (generated by NoteParser on first
  // load) so the UUID is stable across reloads even before the first explicit save.
  const inMemoryId = vaultIndex?.getNoteByPath(relativePath)?.id ?? crypto.randomUUID();
  const merged = mergeForSave(rawExisting, body, { id: inMemoryId });

  await atomicWrite(absPath, merged);
  if (vaultIndex) {
    await vaultIndex.addOrRefresh(absPath);
  }
}

export async function createFile(title: string) {
  if (!currentVaultRoot || !vaultIndex) throw new Error('No vault open');
  const fileName = `${title.replace(/[/\\:*?"<>|]/g, '-')}.md`;
  const absPath = join(currentVaultRoot, fileName);

  // Write frontmatter immediately so the note has a stable id and created date
  // from the very first save (ADR-0006).
  const now = new Date().toISOString();
  const fm: Frontmatter = { id: crypto.randomUUID(), tags: [], created: now, modified: now };
  const content = serializeFrontmatter(fm, `# ${title}\n\n`);

  await atomicWrite(absPath, content);
  return vaultIndex.addOrRefresh(absPath);
}

export async function renameFile(
  relativePath: string,
  newTitle: string
): Promise<{ renamed: import('@notes-app/common').NoteRecord; propagated: import('@notes-app/common').NoteRecord[] }> {
  if (!currentVaultRoot || !vaultIndex) throw new Error('No vault open');
  const oldAbs = join(currentVaultRoot, relativePath);
  const oldTitle = basename(relativePath, '.md');
  const newFileName = `${newTitle.replace(/[/\\:*?"<>|]/g, '-')}.md`;
  const newAbs = join(dirname(oldAbs), newFileName);

  await fs.rename(oldAbs, newAbs);
  vaultIndex.removeByPath(relativePath);
  const renamed = await vaultIndex.addOrRefresh(newAbs);

  // Propagate rename in all notes that link to the old title (ADR-0009)
  const propagated = await propagateRename(oldTitle, newTitle);

  return { renamed, propagated };
}

async function propagateRename(
  oldTitle: string,
  newTitle: string
): Promise<import('@notes-app/common').NoteRecord[]> {
  if (!currentVaultRoot || !vaultIndex) return [];

  const notesWithLink = vaultIndex
    .getAllNotes()
    .filter((n) => n.outlinks.some((l) => l.targetTitle.toLowerCase() === oldTitle.toLowerCase()));

  const updated = await Promise.all(
    notesWithLink.map(async (note) => {
      const absPath = join(currentVaultRoot!, note.path);
      try {
        const content = await fs.readFile(absPath, 'utf-8');
        const replaced = replaceWikiLinkTarget(content, oldTitle, newTitle);
        if (replaced !== content) {
          await atomicWrite(absPath, replaced);
          return vaultIndex!.addOrRefresh(absPath);
        }
      } catch {
        // File may have been deleted concurrently — skip
      }
      return null;
    })
  );

  return updated.filter((r): r is import('@notes-app/common').NoteRecord => r !== null);
}

/**
 * Applies a partial frontmatter patch to a note without changing its body.
 * Used for tag editing and similar in-panel operations.
 */
export async function updateFrontmatter(
  relativePath: string,
  patch: Partial<{ tags: string[]; emoji: string | null }>
): Promise<import('@notes-app/common').NoteRecord> {
  if (!currentVaultRoot || !vaultIndex) throw new Error('No vault open');
  const absPath = join(currentVaultRoot, relativePath);

  const raw = await fs.readFile(absPath, 'utf-8');
  const { frontmatter, body } = parseFrontmatter(raw);

  // Merge patch — filter out undefined/null values that should be removed.
  const merged = { ...frontmatter };
  if (patch.tags !== undefined) merged.tags = [...new Set(patch.tags)];
  if (patch.emoji !== undefined) merged.emoji = patch.emoji ?? undefined;
  merged.modified = new Date().toISOString();

  await atomicWrite(absPath, serializeFrontmatter(merged, body));
  return vaultIndex.addOrRefresh(absPath);
}

export async function deleteFile(relativePath: string): Promise<void> {
  if (!currentVaultRoot || !vaultIndex) throw new Error('No vault open');
  const absPath = join(currentVaultRoot, relativePath);
  await fs.unlink(absPath);
  vaultIndex.removeByPath(relativePath);
}

export async function saveImage(
  base64: string,
  ext: string,
  activeRelativePath: string
): Promise<string> {
  if (!currentVaultRoot) throw new Error('No vault open');

  // Sibling folder convention (ADR-0005): <note-stem>/<uuid>.<ext>
  const noteStem = basename(activeRelativePath, '.md');
  const noteDir = dirname(join(currentVaultRoot, activeRelativePath));
  const siblingDir = join(noteDir, noteStem);

  await fs.mkdir(siblingDir, { recursive: true });
  const fileName = `${crypto.randomUUID()}.${ext}`;
  const absPath = join(siblingDir, fileName);
  await fs.writeFile(absPath, Buffer.from(base64, 'base64'));

  // Return path relative to vault root for use in Markdown
  return relative(currentVaultRoot, absPath);
}

export async function closeVault() {
  await watcher?.close();
  watcher = null;
  vaultIndex = null;
  currentVaultRoot = null;
}
